CREATE TABLE vat_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number TEXT NOT NULL UNIQUE,
  invoice_date DATE NOT NULL,
  seller_name TEXT NOT NULL,
  seller_address TEXT NOT NULL,
  seller_pan TEXT NOT NULL,
  seller_vat_registration_number TEXT NOT NULL,
  buyer_name TEXT NOT NULL,
  buyer_address TEXT NOT NULL,
  buyer_pan TEXT NOT NULL,
  buyer_vat_registration_number TEXT NOT NULL,
  items JSONB NOT NULL,
  sub_total NUMERIC NOT NULL,
  vat_total NUMERIC NOT NULL,
  grand_total NUMERIC NOT NULL,
  payment_mode TEXT NOT NULL,
  paid_amount NUMERIC NOT NULL,
  due_amount NUMERIC NOT NULL,
  remarks TEXT,
  irn TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id)
);
