// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coacymsqarronnlytceu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYWN5bXNxYXJyb25ubHl0Y2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzAxNzIsImV4cCI6MjA2NzcwNjE3Mn0.0Cw2EZ6jkBEMMLZ4qsdErYJesp6VjoQ1tQvbY27qIe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-application-name': 'dashboard-app',
      Accept: "application/json",
    },
  },
});

// Set up auth state change listener for better error handling
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED' && !session) {
    console.log('Token refresh failed, clearing storage');
    localStorage.removeItem('supabase.auth.token');
    localStorage.clear();
    window.location.reload();
  }

  if (event === 'SIGNED_OUT') {
    console.log('User signed out, clearing storage');
    localStorage.removeItem('supabase.auth.token');
  }
});
