// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coacymsqarronnlytceu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYWN5bXNxYXJyb25ubHl0Y2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzAxNzIsImV4cCI6MjA2NzcwNjE3Mn0.0Cw2EZ6jkBEMMLZ4qsdErYJesp6VjoQ1tQvbY27qIe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create auth options conditionally to avoid issues in non-browser environments (SSR, tests)
const isBrowser = typeof window !== 'undefined' && typeof window.localStorage !== 'undefined';

const authOptions = isBrowser
  ? {
      storage: window.localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  : {
      // No-op auth options for server-side or environments without localStorage
      persistSession: false,
      autoRefreshToken: false,
    };

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: authOptions as any,
});
